CREATE TABLE mall.mall_brand
(
	id SMALLINT UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT '品牌ID',
	brand_name VARCHAR(100) NOT NULL COMMENT '品牌名称',
	brand_web VARCHAR(255) NOT NULL DEFAULT '' COMMENT '品牌网址',
	brand_desc VARCHAR(255) NOT NULL DEFAULT '' COMMENT '品牌描述',
	sort int UNSIGNED NOT NULL DEFAULT 100 COMMENT '排序',
	is_show TINYINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '1-显示 0-不显示',
	add_time INT NOT NULL DEFAULT 0 COMMENT '增加时间',
	brand_logo VARCHAR(100) NOT NULL DEFAULT '' COMMENT '品牌LOGO'
)ENGINE myisam CHARSET utf8;